import type { DocSet } from '../types';

/** Main application documentation, rendered under /docs. */
export const appDocs: DocSet = {
  basePath: '/docs',
  title: 'Documentation',
  sections: [
    {
      title: 'Getting Started',
      pages: [
        {
          slug: 'introduction',
          title: 'Introduction',
          description: 'What API Workbench is, what problems it solves, and how it is put together.',
          blocks: [
            { kind: 'p', text: 'API Workbench is a **free, open-source desktop app** for API testing and visual workflow automation. It is offline-first: collections, requests, variables, credentials, workflow definitions, and run history all live in a **local SQLite database** on your machine. There is no account, no mandatory cloud, and no sync service reading your data.' },
            { kind: 'mockup', mockup: 'requests', caption: 'The request editor: collection tree, editor tabs, and response viewer.' },
            { kind: 'h2', text: 'Why another API client?' },
            { kind: 'ul', items: [
              '**Spec-first teams lose edits.** Most clients treat an OpenAPI import as a one-shot snapshot. API Workbench keeps the collection *linked* to its spec: re-syncing diffs and merges, preserving your renames, headers, tests, and examples.',
              '**Automation is bolted on elsewhere.** Here workflows are a core engine — a drag-and-drop canvas with conditions, loops, retries, sub-workflows, and human-in-the-loop prompts, executed deterministically.',
              '**Privacy by architecture.** Secrets are encrypted with your OS keychain and decrypted only in the trusted main process. Plugins run sandboxed with user-approved capabilities.',
            ] },
            { kind: 'h2', text: 'Feature overview' },
            { kind: 'table', head: ['Area', 'What you get'], rows: [
              ['Collections', 'Folders, favourites, history, virtualized search — responsive past 10,000 requests'],
              ['OpenAPI', 'Import 3.x / Swagger 2 from JSON, YAML, or URL; safe re-sync with conflict review'],
              ['Execution', 'REST, GraphQL, gRPC, WebSocket, SSE; streaming, multipart, retries, cancellation'],
              ['Variables', '7 scopes with strict precedence; encrypted secret variables'],
              ['Auth', 'Bearer, OAuth2, Basic, Digest, API Key, Cookies, AWS SigV4, client certificates'],
              ['Testing', 'Assertions, JSON Schema validation, custom JavaScript tests, reports'],
              ['Workflows', 'Visual designer + deterministic runtime with pause/resume and data mapping'],
              ['AI assistant', 'Bring-your-own-key assistant that edits collections, requests & workflows — approval on every write'],
              ['MCP server', 'Author workflows from Claude Desktop, Cursor, Copilot & other MCP clients over a hardened loopback channel'],
              ['Plugins', 'Custom nodes, request types, auth providers, importers — sandboxed'],
            ] },
            { kind: 'callout', tone: 'tip', text: 'New here? Follow the [Quick Start](/docs/quick-start) — you will import a spec and send your first request in under five minutes.' },
          ],
        },
        {
          slug: 'installation',
          title: 'Installation',
          description: 'Install API Workbench on Windows, macOS, or Linux, or build it from source.',
          blocks: [
            { kind: 'p', text: 'API Workbench ships as native installers from the [GitHub Releases](https://github.com/anandhan-j/API-Workbench/releases) page. All builds are unsigned pre-releases until Phase 18 (Security & Packaging) completes — your OS may ask you to confirm the first launch.' },
            { kind: 'tabs', tabs: [
              { label: 'Windows', blocks: [
                { kind: 'p', text: 'Download `API-Workbench-Setup-x64.exe` and run it. A portable ZIP is also published — extract anywhere and run `API Workbench.exe`.' },
              ] },
              { label: 'macOS', blocks: [
                { kind: 'p', text: 'Download the `.dmg`, open it, and drag **API Workbench** into Applications. On first launch, right-click → Open to bypass Gatekeeper for the unsigned pre-release.' },
              ] },
              { label: 'Linux', blocks: [
                { kind: 'code', lang: 'bash', title: 'AppImage', code: 'chmod +x API-Workbench-x86_64.AppImage\n./API-Workbench-x86_64.AppImage' },
                { kind: 'p', text: '`.deb` and `.rpm` packages are also published for Debian/Ubuntu and Fedora/RHEL.' },
              ] },
            ] },
            { kind: 'h2', text: 'Building from source' },
            { kind: 'p', text: 'You need **Node.js 20+** and npm. The repo is an npm-workspaces monorepo; root scripts delegate into the desktop workspace.' },
            { kind: 'code', lang: 'bash', title: 'terminal', code: 'git clone https://github.com/anandhan-j/API-Workbench.git\ncd API-Workbench\nnpm install\nnpm run dev        # development with hot reload\nnpm run dist       # production installers for your platform' },
            { kind: 'callout', tone: 'warning', title: 'Native module note', text: 'Persistence uses `better-sqlite3`, a native module matched to Electron\'s ABI. `npm install` rebuilds it automatically; if the app fails to start with a `NODE_MODULE_VERSION` mismatch, run `npm run rebuild:native`.' },
            { kind: 'h2', text: 'Where data lives' },
            { kind: 'p', text: 'The SQLite database is created in your OS application-data directory on first launch. Use **Settings → Data & Backup** to export a full backup or restore one. Uninstalling the app does not delete your data directory.' },
          ],
        },
        {
          slug: 'quick-start',
          title: 'Quick Start',
          description: 'Import an OpenAPI spec, configure a variable, and send your first request.',
          blocks: [
            { kind: 'p', text: 'This walkthrough takes you from a fresh install to a passing request with tests in about five minutes.' },
            { kind: 'h2', text: '1. Import a spec' },
            { kind: 'ol', items: [
              'Click **Import** in the sidebar (or press `Ctrl+Shift+I`).',
              'Paste a spec URL — try `https://petstore3.swagger.io/api/v3/openapi.json` — or choose a local JSON/YAML file.',
              'Review the preview and confirm. A collection appears with folders per tag and one request per operation.',
            ] },
            { kind: 'h2', text: '2. Set your base URL' },
            { kind: 'p', text: 'Imported requests reference `{{baseUrl}}`. Open the **Variables** panel, pick the *collection* scope, and set it:' },
            { kind: 'code', lang: 'http', title: 'variables → collection scope', code: 'baseUrl = https://petstore3.swagger.io/api/v3' },
            { kind: 'h2', text: '3. Send a request' },
            { kind: 'p', text: 'Open `GET /pet/findByStatus`, set the `status` query param to `available`, and hit **Send** (`Ctrl+Enter`). The response panel shows status, timing, size, headers, and the pretty-printed body.' },
            { kind: 'h2', text: '4. Add a test' },
            { kind: 'p', text: 'Switch to the **Tests** tab and add assertions — no code needed for the common cases:' },
            { kind: 'ul', items: ['Status **equals** `200`', 'Body **JSON path** `$[0].status` equals `available`', 'Response time **less than** `2000` ms'] },
            { kind: 'h2', text: '5. Automate it' },
            { kind: 'p', text: 'Create a workflow, drag the request onto the canvas, add a **condition** on the status code and a **set-variable** node to capture `$[0].id` into `{{petId}}` for the next step. Press **Run** and watch the live log. Continue with [Workflow Basics](/docs/workflow-basics).' },
            { kind: 'callout', tone: 'tip', text: 'Everything you just did is stored locally and versioned — check **History** on the collection to see the automatic import snapshot.' },
          ],
        },
      ],
    },
    {
      title: 'Core Concepts',
      pages: [
        {
          slug: 'workspaces-and-collections',
          title: 'Workspaces & Collections',
          description: 'How work is organized: workspaces, projects, collections, folders, and requests.',
          blocks: [
            { kind: 'p', text: 'API Workbench organizes work in a simple hierarchy: **workspaces** contain **collections**, collections contain **folders and requests**. Each workspace is fully independent — its own variables, credentials, history, and settings — which makes it natural to separate clients, products, or environments.' },
            { kind: 'h2', text: 'Collections' },
            { kind: 'p', text: 'A collection is either **manual** (you build it request by request) or **spec-linked** (created by an OpenAPI import and kept in sync). Both support the same operations: move, copy, inline rename, delete, favourites, and full-text search. Trees are virtualized, so collections with 10,000+ requests stay smooth.' },
            { kind: 'h2', text: 'Requests' },
            { kind: 'p', text: 'A request bundles its method and URL (with `{{variable}}` templates), query params, headers, body, auth config, pre/post scripts, and tests. Non-HTTP request types — GraphQL, gRPC, WebSocket, SSE, or plugin-defined types — live in the same tree with a type badge instead of a method.' },
            { kind: 'h2', text: 'History & favourites' },
            { kind: 'p', text: 'Every execution is recorded in the request history with its resolved URL, status, timing, and response snapshot. Star any request to pin it to the favourites rail.' },
            { kind: 'callout', tone: 'note', text: 'Workspace import/export produces a single portable file including collections and variables — secrets are exported **encrypted** and only restorable on a machine that can decrypt them.' },
          ],
        },
        {
          slug: 'variables-and-secrets',
          title: 'Variables & Secrets',
          description: 'Seven variable scopes, precedence rules, templates, and encrypted secrets.',
          blocks: [
            { kind: 'p', text: 'Variables let one collection serve many environments. Reference them anywhere with `{{name}}` — URLs, headers, bodies, auth configs, workflow node settings, scripts.' },
            { kind: 'mockup', mockup: 'variables', caption: 'The variables panel with mixed scopes and encrypted secrets.' },
            { kind: 'h2', text: 'Scopes & precedence' },
            { kind: 'p', text: 'Seven scopes are resolved lowest to highest — a higher scope shadows a lower one with the same name:' },
            { kind: 'code', lang: 'text', title: 'precedence (low → high)', code: 'global < workspace < collection < folder < request < workflow < runtime' },
            { kind: 'table', head: ['Scope', 'Typical use'], rows: [
              ['global', 'Values shared by every workspace (your name, a default page size)'],
              ['workspace', 'Environment roots: `baseUrl`, `apiKey` for staging vs production'],
              ['collection', 'API-specific values shared by all its requests'],
              ['folder', 'Overrides for one resource group'],
              ['request', 'One-off overrides for a single request'],
              ['workflow', 'Values defined on a workflow definition'],
              ['runtime', 'Values produced *during* a run — extractions, prompts, set-variable nodes'],
            ] },
            { kind: 'p', text: 'Only scopes present in the resolve context participate: sending a bare request uses global→request; a workflow run adds workflow and runtime on top.' },
            { kind: 'h2', text: 'Secret variables' },
            { kind: 'p', text: 'Mark a variable as **secret** and its value is encrypted at rest using your OS keychain (Windows DPAPI, macOS Keychain, libsecret). Decryption happens **only in the main process** at execution time — the UI, scripts panel, and plugin processes only ever see that a value *exists*, never its plaintext.' },
            { kind: 'callout', tone: 'danger', title: 'Secrets never cross the boundary', text: 'The IPC layer omits secret values from every list/get response by design. If you need a secret in a response assertion, assert on the *server\'s* behavior, not the raw secret.' },
            { kind: 'h2', text: 'Dynamic expressions' },
            { kind: 'p', text: 'Templates can include built-in generators — `{{$uuid}}`, `{{$timestamp}}`, `{{$randomInt}}` — evaluated fresh on every execution.' },
          ],
        },
        {
          slug: 'authentication',
          title: 'Authentication',
          description: 'Configure the eight built-in auth schemes and reuse credentials everywhere.',
          blocks: [
            { kind: 'p', text: 'Credentials are stored once in the workspace **credential store** (secret fields encrypted) and attached to requests, folders, or collections by reference. At execution time the auth engine resolves `{{variables}}` inside the config and signs the request.' },
            { kind: 'h2', text: 'Supported schemes' },
            { kind: 'table', head: ['Scheme', 'Notes'], rows: [
              ['Bearer', 'Static token or `{{variable}}`-driven'],
              ['OAuth 2.0', 'Authorization code, client credentials, and password grants with automatic token refresh'],
              ['Basic', 'Username/password, pre-emptive or challenge-response'],
              ['Digest', 'RFC 7616 with automatic nonce handling'],
              ['API Key', 'Header, query parameter, or cookie placement'],
              ['Cookies', 'Managed cookie jar per workspace'],
              ['AWS SigV4', 'Access/secret key signing with region and service'],
              ['Client certificates', 'Per-host mTLS certificates'],
            ] },
            { kind: 'h2', text: 'Inheritance' },
            { kind: 'p', text: 'Auth configured on a folder or collection applies to every request beneath it unless the request overrides it. Workflows resolve a step\'s `credentialId` through the same store — the [workflow engine reuses the execution engine](/docs/architecture) rather than owning its own HTTP path.' },
            { kind: 'callout', tone: 'tip', text: 'Combine auth with workspace variables: keep one `oauth-staging` credential whose token URL is `{{authHost}}/token`, then flip `authHost` per workspace.' },
            { kind: 'p', text: 'Plugins can add entirely new schemes — see [Auth Providers](/plugins/auth-providers) in the Plugin SDK docs.' },
          ],
        },
        {
          slug: 'openapi-import-and-sync',
          title: 'OpenAPI Import & Sync',
          description: 'Generate collections from specs and keep them in sync without losing manual edits.',
          blocks: [
            { kind: 'p', text: 'The import engine accepts **OpenAPI 3.x and Swagger 2**, as JSON or YAML, from a local file or URL. It validates the document, then generates a collection: folders per tag, one request per operation, parameter and body examples, and schema-aware descriptions.' },
            { kind: 'h2', text: 'Synchronization' },
            { kind: 'p', text: 'When the spec changes, **Sync** re-imports it and merges instead of replacing:' },
            { kind: 'mockup', mockup: 'diff', caption: 'The sync review: added, changed, and removed operations before merging.' },
            { kind: 'ol', items: [
              'The **diff engine** compares the new spec against the collection\'s spec snapshot: added, changed, and removed operations.',
              'The **merge engine** applies additions and updates while preserving manual edits — renames, extra headers, bodies, tests, and scripts survive.',
              'Conflicts (you edited a field the spec also changed) are surfaced for review; you pick a side per conflict.',
              'Removed endpoints are flagged rather than silently deleted.',
            ] },
            { kind: 'h2', text: 'Safety net' },
            { kind: 'p', text: 'The app **auto-snapshots the collection before and after** every import and sync. If a merge was not what you wanted, open **History** and restore the pre-sync snapshot in one click — see [Version Control](/docs/version-control).' },
            { kind: 'callout', tone: 'note', text: 'A checksum of the source spec is stored with each snapshot, so you can always tell which spec version a collection state corresponds to.' },
            { kind: 'h2', text: 'Replace mode' },
            { kind: 'p', text: 'If you want a clean slate instead of a merge, choose **Replace** during sync — the collection is regenerated from the spec, and the automatic snapshot still lets you undo.' },
          ],
        },
        {
          slug: 'version-control',
          title: 'Collection Version Control',
          description: 'Snapshots, diffs, and rollback for collections.',
          blocks: [
            { kind: 'p', text: 'Every collection carries a linear history of **snapshots** — full captures of its structure and content. Snapshots are created automatically around imports and syncs, and manually whenever you choose **Snapshot now**.' },
            { kind: 'h2', text: 'Diff viewer' },
            { kind: 'p', text: 'Select any two snapshots to see a structured diff: requests added, removed, or changed, with field-level detail (URL, headers, body, tests). Change summaries are attached to each snapshot so the history reads like a log.' },
            { kind: 'h2', text: 'Restore' },
            { kind: 'p', text: '**Rollback** restores the collection to a snapshot. The current state is snapshotted first, so a rollback is itself reversible. Restoring never touches other collections or your variables.' },
            { kind: 'callout', tone: 'tip', text: 'Snapshot before a risky bulk edit. The snapshot is cheap — storage is deduplicated in SQLite — and undo becomes trivial.' },
          ],
        },
      ],
    },
    {
      title: 'Executing Requests',
      pages: [
        {
          slug: 'sending-requests',
          title: 'Sending Requests',
          description: 'The request editor, execution options, and the response viewer.',
          blocks: [
            { kind: 'p', text: 'The editor gives each request tabs for **Params**, **Headers**, **Body** (raw, JSON, form-data, multipart, binary), **Auth**, **Scripts**, and **Tests**. Every text field accepts `{{variables}}`.' },
            { kind: 'h2', text: 'Execution options' },
            { kind: 'table', head: ['Option', 'Behavior'], rows: [
              ['Timeout', 'Per-request timeout in ms; the default lives in Settings → Network'],
              ['Retries', 'Retry count with backoff for transient network failures'],
              ['Redirects', 'Follow automatically (with a hop limit) or surface the 3xx'],
              ['Streaming', 'Large responses stream to disk instead of buffering in memory'],
              ['Cancellation', 'Every in-flight request can be aborted instantly'],
            ] },
            { kind: 'h2', text: 'The response viewer' },
            { kind: 'p', text: 'Responses render with a status chip, timing and size metrics, headers and cookies tables, and a body view that auto-detects JSON, XML, HTML, text, and binary. JSON gets folding, search, and copy-path.' },
            { kind: 'p', text: 'Uploads support multipart forms and raw binary; downloads stream to a file you pick. Performance metrics break down DNS, connect, TLS, first-byte, and download phases.' },
            { kind: 'callout', tone: 'tip', text: '`Ctrl+Enter` sends the focused request; `Esc` cancels an in-flight execution.' },
          ],
        },
        {
          slug: 'protocols',
          title: 'GraphQL, gRPC, WebSocket & SSE',
          description: 'Multi-protocol execution and live interactive sessions.',
          blocks: [
            { kind: 'p', text: 'Execution is **protocol-agnostic** at the core: every request produces a normalized envelope, and every protocol provider returns a normalized result the response viewer knows how to render. HTTP is simply built-in provider #1 — GraphQL, gRPC, WebSocket, and SSE plug into the same pipeline, as can [plugin request types](/plugins/request-types).' },
            { kind: 'h2', text: 'GraphQL' },
            { kind: 'p', text: 'A dedicated editor for query/mutation text and a JSON variables panel. Errors in the GraphQL `errors` array are surfaced distinctly from transport errors, and the summary chip reflects both.' },
            { kind: 'h2', text: 'gRPC' },
            { kind: 'p', text: 'Unary calls with target, method, metadata, and deadline configuration. Response metadata renders in the standard metadata table; message bodies pretty-print as JSON.' },
            { kind: 'h2', text: 'WebSocket & SSE — interactive sessions' },
            { kind: 'p', text: 'Interactive request types open a **live session** instead of a one-shot execution. The session panel shows a scrolling event log — sent frames, received frames, info, and errors — with connection state and close controls. WebSocket sessions can send text frames from an input bar; SSE sessions tag events by name.' },
            { kind: 'callout', tone: 'note', text: 'In workflows, interactive types run in one-shot mode (connect → first response or timeout) so runs remain deterministic.' },
          ],
        },
        {
          slug: 'testing-and-scripting',
          title: 'Testing & Scripting',
          description: 'Assertions, JSON Schema validation, custom JavaScript tests, and pre/post scripts.',
          blocks: [
            { kind: 'p', text: 'Every request can carry **assertions** and **scripts**; both run automatically on each execution (standalone or inside a workflow) and report into the test panel and run logs.' },
            { kind: 'h2', text: 'Declarative assertions' },
            { kind: 'ul', items: [
              '**Status** — equals / in-range checks on the status code or protocol summary code.',
              '**Headers** — presence, equality, or regex match on any response header.',
              '**Body** — JSONPath expressions with equals/contains/regex/type operators.',
              '**JSON Schema** — validate the whole body against a schema (imported schemas are available by reference).',
              '**Timing** — response-time budgets.',
            ] },
            { kind: 'h2', text: 'Custom JavaScript tests' },
            { kind: 'code', lang: 'ts', title: 'Tests tab', code: "test('creates the charge', () => {\n  expect(response.status).toBe(201);\n  const body = response.json();\n  expect(body.status).toBe('succeeded');\n  expect(body.amount).toBeGreaterThan(0);\n});" },
            { kind: 'h2', text: 'Pre-request & post-response scripts' },
            { kind: 'p', text: 'Scripts run in a **sandbox** with no filesystem or Node access. They can read and write variables, inspect the request/response, and log to the console panel:' },
            { kind: 'code', lang: 'ts', title: 'Pre-request script', code: "// sign the request with a fresh nonce\nconst nonce = wb.uuid();\nwb.variables.set('runtime', 'nonce', nonce);\nwb.request.headers['X-Nonce'] = nonce;" },
            { kind: 'code', lang: 'ts', title: 'Post-response script', code: "// capture the auth token for later requests\nconst { token } = wb.response.json();\nwb.variables.set('runtime', 'authToken', token);" },
            { kind: 'callout', tone: 'warning', text: 'Scripts intentionally cannot read secret variable plaintext; reference secrets with `{{secretName}}` templates in the request itself, where substitution happens in the main process.' },
          ],
        },
      ],
    },
    {
      title: 'Workflows',
      pages: [
        {
          slug: 'workflow-basics',
          title: 'Workflow Basics',
          description: 'The visual designer, runs, and how data moves between steps.',
          blocks: [
            { kind: 'p', text: 'A workflow is a graph of **nodes** on a canvas, executed deterministically by the runtime. Drag nodes from the palette (or requests straight from a collection), connect them, configure each one, and press **Run**.' },
            { kind: 'mockup', mockup: 'workflow', caption: 'The designer: request, condition, loop, and set-variable nodes wired together.' },
            { kind: 'h2', text: 'The canvas' },
            { kind: 'p', text: 'Built on React Flow: pan/zoom, multi-select, grouping, copy/paste, undo/redo, and a mini map. Edges from branching nodes are labelled (`true`/`false`, switch cases, `approved`/`rejected`).' },
            { kind: 'h2', text: 'How data flows' },
            { kind: 'p', text: 'Each run owns a mutable **runtime variable map**. Nodes read `{{variables}}` from it and write results back — extractions, prompt answers, set-variable nodes, and plugin node outputs all land in runtime scope, which has the [highest precedence](/docs/variables-and-secrets). That map is the *only* channel between steps, which is what keeps runs reproducible.' },
            { kind: 'h2', text: 'Runs' },
            { kind: 'p', text: 'The run panel shows each step live: status, duration, request/response snapshots, assertion results, and log lines. Long runs can be **paused, resumed, or cancelled**; failed steps honour per-node retry policies before the error handler routes the flow.' },
            { kind: 'callout', tone: 'tip', text: 'Workflow request steps reuse your stored credentials and the same execution engine as manual requests — a request that works in the editor behaves identically inside a workflow.' },
          ],
        },
        {
          slug: 'workflow-nodes',
          title: 'Node Reference',
          description: 'Every built-in workflow node and its configuration.',
          blocks: [
            { kind: 'p', text: 'Built-in nodes cover control flow, data, and interaction. Plugins add more under their own category — see [Workflow Nodes](/plugins/workflow-nodes) in the SDK docs.' },
            { kind: 'table', head: ['Node', 'Category', 'What it does'], rows: [
              ['Request', 'Execute', 'Runs a collection request (or an inline one); exposes status, headers, and body to extraction'],
              ['Condition', 'Control', 'Routes along `true`/`false` based on an expression over runtime variables'],
              ['Switch', 'Control', 'Multi-way routing on a value; each case is a labelled edge'],
              ['Loop', 'Control', 'Iterates an array (from JSONPath/JMESPath) or a counted range; body is a sub-graph'],
              ['Parallel', 'Control', 'Fans out into concurrent branches and joins on completion'],
              ['Delay', 'Control', 'Waits a fixed or variable duration'],
              ['Set Variable', 'Data', 'Writes one or more runtime variables from templates or extractions'],
              ['Extract', 'Data', 'Pulls values out of the previous response via JSONPath, JMESPath, or regex'],
              ['Transform', 'Data', 'Applies an expression to reshape a value before storing it'],
              ['User Input', 'Interact', 'Pauses and prompts with typed fields; answers merge into runtime variables'],
              ['Sub-workflow', 'Compose', 'Runs another workflow with its own inputs; its runtime writes propagate back'],
              ['Terminate', 'Control', 'Ends the run early with success or failure'],
            ] },
            { kind: 'h2', text: 'Error handling & retries' },
            { kind: 'p', text: 'Every node accepts a **retry policy** (attempts, backoff) and a **timeout**. A node that still fails routes along its `error` edge if connected; otherwise the run fails with the node\'s error attached to the log.' },
            { kind: 'h2', text: 'Prompting mid-run' },
            { kind: 'p', text: 'The **User Input** node shows a native modal with fields you define — string, secret, number, boolean, select, or key-value grid. Defaults are templates evaluated against the current run, and submitted values become runtime variables, so approvals and parameterized reruns need no scripting.' },
          ],
        },
        {
          slug: 'data-mapping',
          title: 'Data Mapping & Transformations',
          description: 'JSONPath, JMESPath, regex extraction, and the expression editor.',
          blocks: [
            { kind: 'p', text: 'Moving data between steps is the heart of workflow automation. API Workbench gives you three extraction languages and a visual mapper with live preview.' },
            { kind: 'h2', text: 'Extraction' },
            { kind: 'tabs', tabs: [
              { label: 'JSONPath', blocks: [
                { kind: 'code', lang: 'text', code: '$.items[0].id          → first item id\n$.items[*].price       → all prices\n$..address.city        → any nested city' },
              ] },
              { label: 'JMESPath', blocks: [
                { kind: 'code', lang: 'text', code: "items[?status=='active'].id    → ids of active items\nitems | length(@)              → count\nreverse(sort_by(items, &age))  → sorted projection" },
              ] },
              { label: 'Regex', blocks: [
                { kind: 'code', lang: 'text', code: 'Location: /orders/(\\d+)   → capture group 1 = order id' },
                { kind: 'p', text: 'Regex extraction works on headers and text bodies; the first capture group is stored.' },
              ] },
            ] },
            { kind: 'h2', text: 'The expression editor' },
            { kind: 'p', text: 'Wherever an expression is accepted, the editor offers `{{…}}` **autocomplete for every runtime variable** known at that point in the graph — including variables plugin nodes declare they produce — plus a live preview pane evaluating against the last run\'s data.' },
            { kind: 'h2', text: 'Visual mapping' },
            { kind: 'p', text: 'The mapper shows the previous step\'s response tree on the left and the next request\'s fields on the right; drag a leaf onto a field to create the extraction + template automatically.' },
            { kind: 'callout', tone: 'tip', text: 'Runtime variables are strings. Numbers and booleans are stored in their string form and coerced by conditions — write `{{count}} > 3`, not `parseInt`.' },
          ],
        },
      ],
    },
    {
      title: 'AI & MCP',
      pages: [
        {
          slug: 'ai-assistant',
          title: 'AI Assistant',
          description: 'A bring-your-own-key assistant that operates on your collections, requests, workflows, and variables — with approval on every write.',
          blocks: [
            { kind: 'p', text: 'API Workbench ships a built-in AI assistant that works on your **actual data** — it can browse and edit collections, create and update requests, draft and run workflows, and manage non-secret variables through the app\'s own service methods. It is **bring-your-own-key** and strictly opt-in: with no provider configured it makes no network calls at all, preserving the offline-first posture.' },
            { kind: 'callout', tone: 'note', text: 'The assistant is scope-locked to your API work inside the app. It will decline general-knowledge questions, coding help unrelated to your APIs, and chit-chat — by design.' },
            { kind: 'h2', text: 'Connect a provider' },
            { kind: 'p', text: 'Open **Settings → AI** and add a provider. One provider layer covers Anthropic Claude directly and every OpenAI-compatible endpoint through a configurable base URL:' },
            { kind: 'table', head: ['Provider', 'Notes'], rows: [
              ['Anthropic Claude', 'Official SDK, native tool use, streaming; default model `claude-opus-4-8`.'],
              ['OpenAI', 'Chat-completions wire format; GPT models.'],
              ['DeepSeek / Groq / OpenRouter', 'OpenAI-compatible — just set the base URL and model.'],
              ['Ollama (local)', 'Point the base URL at your local server for fully offline inference.'],
            ] },
            { kind: 'p', text: 'Your API key is encrypted with the OS keychain and **decrypted only in the main process** — exactly like secret variables. The DTO that crosses to the UI exposes only `hasKey`; the plaintext key never reaches the renderer. Use **Verify key** to make one cheap models-list call and confirm the connection.' },
            { kind: 'h2', text: 'How it works' },
            { kind: 'p', text: 'The assistant runs an agent loop in the main process, where the services and decrypted keys already live. It calls a curated set of tools grouped by risk tier — read tools run immediately; write and execute tools are gated:' },
            { kind: 'table', head: ['Tier', 'Examples', 'Gate'], rows: [
              ['Read', 'list/search collections & requests, get request, list workflows, workflow schema, list variables (masked)', 'Runs immediately'],
              ['Write', 'create/update request, create folder, set non-secret variable, create/validate workflow', 'Per-call approval, with an “allow writes for this chat” opt-in'],
              ['Execute', 'run workflow (live requests)', 'Always confirmed, never batched'],
            ] },
            { kind: 'h2', text: 'Safety rails' },
            { kind: 'ul', items: [
              '**Approve before it writes** — a pending tool call streams to the chat as a card with the arguments; you Approve or Deny. A denial feeds an error result back so the model can adjust.',
              '**Auto-snapshot** — before the first mutating call of a turn, the versioning service snapshots the touched collection (the same pattern as OpenAPI import/sync), so every AI edit is one-click reversible.',
              '**Secrets never reach the model** — variable listings go through the masking path; there is no tool that returns secret plaintext, and no tool to set a secret.',
              '**Prompt-injection containment** — a request\'s response body is untrusted text; the confirmation gate on every write and run is the structural backstop, so injected instructions cannot mutate anything without your click.',
            ] },
            { kind: 'callout', tone: 'tip', text: 'Paste a cURL command into the chat and the assistant parses it and offers to create the matching request. Describe a flow across existing requests and it assembles, validates, and saves the workflow — pending your approval.' },
          ],
        },
        {
          slug: 'mcp-server',
          title: 'MCP Server',
          description: 'Let Claude Desktop, Cursor, Copilot, and other MCP clients author workflows against the app’s real schema and import them into your project.',
          blocks: [
            { kind: 'p', text: 'The **Model Context Protocol** server lets *external* AI clients author API Workbench workflows. It ships as a standalone, transport-agnostic package (`@api-workbench/workflow-mcp`) and the desktop app can spawn and manage it as a child process — so you get the same tooling whether you run it by hand or from inside the app.' },
            { kind: 'h2', text: 'What it exposes' },
            { kind: 'ul', items: [
              '**Resources** — `workflow://schema`, `workflow://schema/graph`, and templated `workflow://examples/{name}`.',
              '**Tools** — `get_workflow_schema`, `validate_workflow`, `generate_workflow`, `add_or_update_workflow`, and `import_workflow_to_app`.',
              '**Prompt** — `create_workflow_from_description` for one-shot authoring.',
            ] },
            { kind: 'callout', tone: 'note', text: 'The workflow JSON Schema is **generated from the app’s Zod domain model** by a committed build step, so the schema an assistant sees can never drift from what the app actually accepts.' },
            { kind: 'h2', text: 'Two ways to run it' },
            { kind: 'tabs', tabs: [
              { label: 'Standalone (stdio)', blocks: [
                { kind: 'p', text: 'Run the package directly for schema, examples, validation, and file output — no desktop app required. `stdout` is the JSON-RPC channel; diagnostics go to `stderr`.' },
                { kind: 'code', lang: 'bash', title: 'terminal', code: 'npx @api-workbench/workflow-mcp' },
              ] },
              { label: 'App-managed (HTTP)', blocks: [
                { kind: 'p', text: 'From **Settings → MCP**, start the server. The app spawns the child in Streamable HTTP mode over loopback and shows you the connect URL and token. In this mode `import_workflow_to_app` imports a finished workflow directly into your open project as a **new** workflow (fresh ids, non-destructive).' },
                { kind: 'code', lang: 'json', title: 'MCP client config', code: '{\n  "mcpServers": {\n    "api-workbench": {\n      "url": "https://127.0.0.1:7337/mcp?token=YOUR_TOKEN"\n    }\n  }\n}' },
              ] },
            ] },
            { kind: 'h2', text: 'Security model' },
            { kind: 'p', text: 'Because the app stores secrets and executes real requests, any listener it opens is part of the attack surface. In HTTP mode three protections are always on:' },
            { kind: 'ul', items: [
              '**Loopback-only bind** (`127.0.0.1`) — never a routable interface.',
              '**Bearer token** on every request (query `?token=` or `Authorization: Bearer`), compared timing-safe; missing or invalid → 401. The token is persisted so the URL is stable, rotated only on explicit refresh, and redacted in every log.',
              '**Origin validation** — native clients (no Origin) or loopback origins only; a real web origin → 403, defeating DNS-rebinding.',
            ] },
            { kind: 'p', text: 'Plus resource caps, and **orphan prevention**: the child treats its stdin closing as parent-death and exits, so an ungraceful app crash never leaves a server running. **TLS is default-on** — the app generates an ephemeral self-signed cert and passes the PEM to the child in memory, so the private key never touches disk.' },
            { kind: 'callout', tone: 'warning', text: 'Start/stop is user-initiated from Settings — the server is never auto-started at boot. Some clients reject self-signed certs; the UI lets you opt down to plain HTTP if you understand the trade-off.' },
          ],
        },
      ],
    },
    {
      title: 'Reference',
      pages: [
        {
          slug: 'architecture',
          title: 'Architecture',
          description: 'The three-process Electron model, the IPC contract, and the security posture.',
          blocks: [
            { kind: 'p', text: 'API Workbench is built as a strictly separated three-process Electron app. Understanding the split explains most of its security and reliability properties.' },
            { kind: 'table', head: ['Process', 'Role'], rows: [
              ['**Main**', 'Node process owning the database, filesystem, network execution, secrets, and all business logic — organized into feature modules (persistence, openapi, execution, variables, auth, workflows, plugins…)'],
              ['**Renderer**', 'The React UI. Sandboxed, no Node access, hash routing. Talks to main only through the typed bridge'],
              ['**Preload**', 'The only bridge: exposes `window.workbench` via contextBridge with an **allowlist** of channels — no generic invoke escape hatch'],
              ['**Plugin host**', 'A fourth, *unprivileged* utility process where all third-party plugin code runs (ADR-0010)'],
            ] },
            { kind: 'h2', text: 'The IPC contract' },
            { kind: 'p', text: 'A single shared module defines every cross-process channel with **Zod schemas for request and response**. The main-process registry validates every inbound request *and* outbound response; a validation failure is rejected and logged, never processed. The renderer client is fully typed off the same contract, so the wire format cannot drift.' },
            { kind: 'h2', text: 'Security posture' },
            { kind: 'ul', items: [
              'Context isolation **on**, node integration **off**, sandbox **on** (ADR-0003).',
              'Navigation and new-window creation blocked in the renderer.',
              'Secrets decrypt only in main; DTOs expose `hasValue`, never plaintext.',
              'Plugin host cannot import Electron or main modules (enforced by lint fences) and reaches main only via a Zod-validated RPC with capability checks on every call.',
            ] },
            { kind: 'h2', text: 'Storage' },
            { kind: 'p', text: 'SQLite via Drizzle with **append-only numbered migrations** — released migrations are checksummed and tampering is rejected. Tests run the same persistence layer against pure-WASM `sql.js`, keeping the suite native-build-free.' },
            { kind: 'p', text: 'Design intent is documented as ADRs in the repo under `docs/adr/` — start with 0003 (IPC/security), 0004 (persistence), 0005/0008 (workflow engine), 0006 (secrets), and 0007/0009/0010 (plugins).' },
          ],
        },
        {
          slug: 'keyboard-shortcuts',
          title: 'Keyboard Shortcuts',
          description: 'The default keymap.',
          blocks: [
            { kind: 'p', text: 'Defaults shown for Windows/Linux; on macOS substitute `Cmd` for `Ctrl`.' },
            { kind: 'table', head: ['Shortcut', 'Action'], rows: [
              ['`Ctrl+K`', 'Command palette / search'],
              ['`Ctrl+Enter`', 'Send request / run workflow'],
              ['`Esc`', 'Cancel in-flight execution'],
              ['`Ctrl+T`', 'New request tab'],
              ['`Ctrl+W`', 'Close tab'],
              ['`Ctrl+Shift+I`', 'Import (OpenAPI / plugin importers)'],
              ['`Ctrl+S`', 'Save request'],
              ['`Ctrl+D`', 'Duplicate request'],
              ['`F2`', 'Rename collection / folder / request inline'],
              ['`Ctrl+Z` / `Ctrl+Shift+Z`', 'Undo / redo on the workflow canvas'],
              ['`Ctrl+C` / `Ctrl+V`', 'Copy / paste nodes on the canvas'],
              ['`Ctrl+,`', 'Settings'],
            ] },
            { kind: 'callout', tone: 'note', text: 'The full keymap is editable under **Settings → Shortcuts**.' },
          ],
        },
        {
          slug: 'troubleshooting',
          title: 'Troubleshooting',
          description: 'Common problems and their fixes.',
          blocks: [
            { kind: 'h2', text: 'The app fails to start after building from source' },
            { kind: 'p', text: 'Almost always a `better-sqlite3` ABI mismatch (`NODE_MODULE_VERSION` error). Rebuild the native module against Electron:' },
            { kind: 'code', lang: 'bash', code: 'npm run rebuild:native' },
            { kind: 'h2', text: 'Requests work in the browser but fail here' },
            { kind: 'ul', items: [
              'Check proxy settings — corporate proxies need configuring under **Settings → Network**.',
              'Self-signed TLS: enable *Allow invalid certificates* per workspace (never globally) or add the CA to your OS store.',
              'Cookies: the app has its own cookie jar per workspace; a session cookie from your browser is not shared.',
            ] },
            { kind: 'h2', text: 'A sync produced an unexpected merge' },
            { kind: 'p', text: 'Open the collection **History** — a snapshot was taken automatically before the sync. Restore it, then re-run the sync and review the conflict list carefully; choose *Replace mode* if you want the spec to win everywhere.' },
            { kind: 'h2', text: 'A secret variable resolves as empty' },
            { kind: 'p', text: 'Secrets can only be decrypted on the machine (and OS user) that encrypted them. After restoring a backup on new hardware, re-enter secret values.' },
            { kind: 'h2', text: 'A plugin fails to activate' },
            { kind: 'p', text: 'Check the plugin log in **Plugin Manager → details**. The two most common causes: the manifest declares a contribution `activate()` never registered (rejected by design), or the SDK engine range does not satisfy the host\'s SDK version. See [Plugin Troubleshooting](/plugins/troubleshooting).' },
            { kind: 'callout', tone: 'tip', text: 'Still stuck? [Open an issue](https://github.com/anandhan-j/API-Workbench/issues) with logs from **Help → Open log folder**.' },
          ],
        },
      ],
    },
  ],
};
