import type { DocSet } from '../types';

/** Plugin SDK documentation, rendered under /plugins. */
export const pluginDocs: DocSet = {
  basePath: '/plugins',
  title: 'Plugin SDK',
  sections: [
    {
      title: 'Getting Started',
      pages: [
        {
          slug: 'introduction',
          title: 'Introduction',
          description: 'What plugins can do, how they are structured, and the design principles behind the SDK.',
          blocks: [
            { kind: 'p', text: 'The Plugin SDK lets you extend API Workbench **without modifying the core**. A plugin is a small package — a `manifest.json` plus one bundled CommonJS module — that contributes to any of four extension points:' },
            { kind: 'table', head: ['Extension point', 'What it adds', 'Example'], rows: [
              ['[Workflow nodes](/plugins/workflow-nodes)', 'Custom steps on the workflow canvas', 'A UUID generator, an approval gate'],
              ['[Request types](/plugins/request-types)', 'New protocols with their own editor', 'MQTT, a message-queue client'],
              ['[Auth providers](/plugins/auth-providers)', 'Custom request signing schemes', 'HMAC header signing'],
              ['[Importers](/plugins/importers)', 'New collection import formats', 'CSV, HAR, Postman dumps'],
            ] },
            { kind: 'mockup', mockup: 'plugins', caption: 'The Plugin Manager: install, enable, and grant capabilities.' },
            { kind: 'h2', text: 'Design principles' },
            { kind: 'ul', items: [
              '**Declarative surface, imperative core.** Everything the app must *display* — config forms, editors, labels, icons — is declared in the manifest as data. Only *behavior* lives in code.',
              '**Sandboxed by default.** Plugin code runs in an isolated utility process with no Electron, DOM, or filesystem access ([architecture](/plugins/architecture)).',
              '**Capabilities, not trust.** Network, variable access, and dialogs each require a user-approved grant, enforced by the host on every call ([permissions](/plugins/capabilities-and-permissions)).',
              '**Types-only contract.** `@api-workbench/plugin-sdk` ships only TypeScript types and one identity helper — nothing to link against, nothing to version-conflict.',
            ] },
            { kind: 'h2', text: 'A complete plugin in 20 lines' },
            { kind: 'code', lang: 'ts', title: 'src/index.ts', code: "import { definePlugin } from '@api-workbench/plugin-sdk';\nimport { randomUUID } from 'node:crypto';\n\nexport default definePlugin({\n  activate(ctx) {\n    ctx.registerNodeExecutor('uuid', {\n      async execute({ config }) {\n        const variable = String(config.variable ?? 'uuid');\n        return {\n          message: `Generated ${variable}`,\n          variables: { [variable]: randomUUID() },\n        };\n      },\n    });\n  },\n});" },
            { kind: 'callout', tone: 'tip', text: 'Jump straight to the [Quick Start](/plugins/quick-start) to scaffold, build, and install this plugin, or browse the eight [example plugins](/examples) shipped in the repo.' },
          ],
        },
        {
          slug: 'architecture',
          title: 'Plugin Architecture',
          description: 'The sandboxed host process, the RPC bridge, and how contributions reach the app.',
          blocks: [
            { kind: 'p', text: 'Plugin execution is built around one rule: **third-party code never runs in a privileged process** (ADR-0010).' },
            { kind: 'h2', text: 'The host process' },
            { kind: 'p', text: 'All plugin code is loaded into a dedicated Electron **utility process** — the plugin host. It has no access to Electron APIs, the DOM, or the database. A lint fence in the repo even forbids the host bundle from importing `electron` or main-process modules.' },
            { kind: 'h2', text: 'The RPC bridge' },
            { kind: 'p', text: 'The host talks to the main process over a **Zod-validated RPC**: every message crossing the boundary is schema-checked on both sides, exactly like the app\'s own IPC contract. When a workflow reaches a plugin node, main sends an `execute` RPC to the host, the host runs your executor, and the validated result comes back.' },
            { kind: 'code', lang: 'text', title: 'call path', code: 'renderer (canvas)\n  → main (workflow engine, registry: plugin:com.acme.tools/uuid)\n    → plugin host (your NodeExecutor.execute)\n  ← validated NodeExecuteResult\n← run log + runtime variables' },
            { kind: 'h2', text: 'The capability broker' },
            { kind: 'p', text: 'Calls initiated *by the plugin* — `ctx.fetch`, `ctx.variables`, `ctx.ui.showDialog` — pass through a **capability broker** in main that checks the user\'s grants for that specific plugin on **every call**, not just at install time. Ungranted calls reject; the corresponding `ctx` property is simply absent.' },
            { kind: 'h2', text: 'Registries & namespacing' },
            { kind: 'p', text: 'Built-in nodes, request types, auth providers, and importers live in four registries seeded at startup. Activating a plugin adds its contributions under the id `plugin:<pluginId>/<key>` — collisions with built-ins are impossible, and disabling a plugin removes its entries atomically.' },
            { kind: 'callout', tone: 'note', text: 'Validated inputs flow *in* (your executor receives config already checked against your declared form schema) and validated outputs flow *out* (the host checks your return value before main uses it). A misbehaving plugin can fail its own step, never corrupt a run.' },
          ],
        },
        {
          slug: 'lifecycle',
          title: 'Plugin Lifecycle',
          description: 'Install, validate, activate, execute, deactivate, uninstall.',
          blocks: [
            { kind: 'p', text: 'A plugin moves through a strict lifecycle; understanding it explains most activation errors.' },
            { kind: 'ol', items: [
              '**Install** — the user picks a plugin package. The loader validates the manifest against the host\'s Zod schema, checks the SDK engine range, and shows the declared capabilities for approval.',
              '**Enable/Activate** — the host process loads your `main` module and calls `activate(context)`. Your code registers one implementation per declared contribution.',
              '**Registration check** — activation fails unless registrations match the manifest *exactly*: every declared contribution registered, nothing extra.',
              '**Execute** — contributions serve calls (node executes, request executes, auth applies, importer parses) until the plugin is disabled.',
              '**Deactivate** — on disable, uninstall, or app shutdown, `deactivate()` (if exported) is awaited so you can flush state; then the module is disposed.',
              '**Uninstall** — the package is removed. Per-plugin storage is deleted; granted capabilities are revoked.',
            ] },
            { kind: 'code', lang: 'ts', title: 'src/index.ts', code: "import { definePlugin } from '@api-workbench/plugin-sdk';\n\nexport default definePlugin({\n  async activate(ctx) {\n    ctx.log.info('activating');\n    ctx.registerNodeExecutor('my-node', executor);   // must match manifest\n  },\n  async deactivate() {\n    // close connections, flush caches — keep it fast\n  },\n});" },
            { kind: 'callout', tone: 'warning', title: 'Symmetric registration', text: 'Registering a kind you did not declare — or forgetting one you did — rejects activation (ADR-0007). The manifest is the single source of truth for what a plugin contributes.' },
            { kind: 'h2', text: 'Failure isolation' },
            { kind: 'p', text: 'An executor that throws fails **its own step** with the error attached to the run log. A crash of the host process is recovered by the host manager; the app itself is unaffected.' },
          ],
        },
        {
          slug: 'quick-start',
          title: 'Quick Start & Template',
          description: 'Scaffold, build, and install your first plugin.',
          blocks: [
            { kind: 'p', text: 'The fastest path is copying one of the [example plugins](/examples) — `uuid-node` is the minimal template. Here is the same thing from scratch.' },
            { kind: 'h2', text: '1. Project setup' },
            { kind: 'code', lang: 'bash', code: 'mkdir my-plugin && cd my-plugin\nnpm init -y\nnpm install -D typescript esbuild @api-workbench/plugin-sdk' },
            { kind: 'h2', text: '2. The manifest' },
            { kind: 'code', lang: 'json', title: 'manifest.json', code: '{\n  "manifestVersion": 1,\n  "id": "com.example.my-plugin",\n  "name": "My Plugin",\n  "version": "1.0.0",\n  "description": "Generates a UUID into a runtime variable.",\n  "main": "dist/index.cjs",\n  "engines": { "sdk": "^1.0.0" },\n  "contributes": {\n    "nodes": [\n      {\n        "kind": "uuid",\n        "label": "Generate UUID",\n        "icon": "hash",\n        "category": "Utilities",\n        "configSchema": {\n          "fields": [\n            {\n              "key": "variable",\n              "kind": "string",\n              "label": "Variable name",\n              "default": "uuid",\n              "required": true\n            }\n          ]\n        },\n        "producesVariables": [{ "source": "config", "key": "variable" }]\n      }\n    ]\n  }\n}' },
            { kind: 'h2', text: '3. The entry module' },
            { kind: 'code', lang: 'ts', title: 'src/index.ts', code: "import { definePlugin } from '@api-workbench/plugin-sdk';\nimport { randomUUID } from 'node:crypto';\n\nexport default definePlugin({\n  activate(ctx) {\n    ctx.registerNodeExecutor('uuid', {\n      async execute({ config }) {\n        const name = String(config.variable);\n        return { variables: { [name]: randomUUID() } };\n      },\n    });\n  },\n});" },
            { kind: 'h2', text: '4. Bundle' },
            { kind: 'p', text: 'The `main` entry must be a **single CommonJS file** — bundle your dependencies:' },
            { kind: 'code', lang: 'bash', code: 'npx esbuild src/index.ts --bundle --platform=node --format=cjs --outfile=dist/index.cjs' },
            { kind: 'h2', text: '5. Install & try it' },
            { kind: 'p', text: 'In API Workbench open **Plugin Manager → Install from file…** and pick your plugin folder (or a zip of it). Approve the (empty) capability list, then drop your **Generate UUID** node onto any workflow — the variable it writes shows up in `{{…}}` autocomplete on later steps thanks to `producesVariables`.' },
            { kind: 'callout', tone: 'tip', text: 'The repo\'s `plugins/examples/build.mjs` shows a minimal shared esbuild script used by all eight examples.' },
          ],
        },
      ],
    },
    {
      title: 'The Manifest',
      pages: [
        {
          slug: 'manifest',
          title: 'Manifest Reference',
          description: 'Every field of manifest.json.',
          blocks: [
            { kind: 'p', text: '`manifest.json` sits at the plugin package root. It is everything the host needs to **list, install, and render** your plugin — only behavior lives in the entry module.' },
            { kind: 'table', head: ['Field', 'Type', 'Notes'], rows: [
              ['`manifestVersion`', '`1`', 'Always the literal `1` today'],
              ['`id`', 'string', 'Reverse-DNS, e.g. `com.acme.tools`. Immutable once published'],
              ['`name`', 'string', 'Display name'],
              ['`version`', 'string', 'The plugin\'s own semver'],
              ['`description`', 'string?', 'Shown in the Plugin Manager'],
              ['`publisher`', 'string?', 'Author or organization'],
              ['`homepage`', 'string?', 'Docs / repo URL'],
              ['`license`', 'string?', 'SPDX identifier'],
              ['`main`', 'string', 'Relative path to the bundled CJS entry, e.g. `dist/index.cjs`'],
              ['`engines.sdk`', 'string', 'Semver range the host SDK must satisfy, e.g. `^1.0.0`'],
              ['`capabilities`', 'Capability[]?', 'See [Capabilities & Permissions](/plugins/capabilities-and-permissions)'],
              ['`contributes`', 'object?', '`nodes`, `requestTypes`, `authProviders`, `importers` arrays'],
              ['`signature`', 'string?', 'Reserved for marketplace signing; ignored in v1'],
            ] },
            { kind: 'h2', text: 'Contribution keys' },
            { kind: 'p', text: 'Each contribution has an unqualified key (`kind`, `type`, or `id`) matching `[a-z][a-z0-9-]*`. At runtime it is addressed as `plugin:<pluginId>/<key>` — e.g. `plugin:com.acme.tools/uuid` — so plugins can never collide with built-ins or each other.' },
            { kind: 'h2', text: 'Icons' },
            { kind: 'p', text: 'The `icon` fields name a **lucide icon** from the host\'s allowlist. Unknown names fall back to a puzzle piece; there is no way to ship arbitrary image assets in v1, which keeps packages inert.' },
            { kind: 'callout', tone: 'note', text: 'The SDK\'s `PluginManifest` type mirrors the host\'s Zod schema exactly, so `satisfies PluginManifest` on a typed manifest object gives you compile-time validation.' },
          ],
        },
        {
          slug: 'capabilities-and-permissions',
          title: 'Capabilities & Permissions',
          description: 'The grant model: what plugins may request and how enforcement works.',
          blocks: [
            { kind: 'p', text: 'Per-plugin **storage** and **logging** are always available. Everything else is a capability: declared in the manifest, shown to the user at install time, and enforced by the broker on every call.' },
            { kind: 'table', head: ['Capability', 'Grants', 'Context surface'], rows: [
              ['`network`', 'Outbound HTTP', '`ctx.fetch` (standard fetch API)'],
              ['`variables:read`', 'Resolve `{{variable}}` templates', '`ctx.variables.resolve(template)`'],
              ['`variables:write`', 'Set workspace/global variables', '`ctx.variables.set(scope, key, value)`'],
              ['`ui:dialog`', 'Host-rendered modal dialogs', '`ctx.ui.showDialog(options)`'],
            ] },
            { kind: 'h2', text: 'Enforcement model' },
            { kind: 'ul', items: [
              'Undeclared → the context property is `undefined`; your code must handle absence.',
              'Declared but denied by the user → same: absent. Design features to degrade.',
              'Granted → present, but **every call** still passes the broker, so a revoked grant takes effect immediately.',
            ] },
            { kind: 'code', lang: 'ts', title: 'defensive capability use', code: "async execute({ config }) {\n  if (!ctx.fetch) {\n    return { message: 'Network capability not granted — skipping enrichment' };\n  }\n  const res = await ctx.fetch(String(config.url));\n  return { variables: { status: String(res.status) } };\n}" },
            { kind: 'callout', tone: 'danger', title: 'Secrets stay out of reach', text: '`variables:read` resolves templates — but secret values are substituted inside the main process, and resolution results that would leak secret plaintext to plugins are refused. Never ask users to paste secrets into non-secret config fields.' },
            { kind: 'h2', text: 'Requesting the minimum' },
            { kind: 'p', text: 'Users see the capability list as your plugin\'s **blast radius**. A UUID generator asking for `network` will (rightly) look suspicious. Split ambitious plugins into narrower ones instead of accumulating grants.' },
          ],
        },
        {
          slug: 'forms',
          title: 'Form Schemas',
          description: 'The declarative form language driving config editors, payload editors, and dialogs.',
          blocks: [
            { kind: 'p', text: 'Plugins never render UI. Wherever configuration is needed — node config, credential editors, request payload editors, dialogs — you declare a **FormSchema** and the host renders it with its own trusted components, validates submissions, and hands your code the values.' },
            { kind: 'code', lang: 'ts', title: 'FormSchema', code: "{\n  fields: [\n    { key: 'url',     kind: 'string',  label: 'Endpoint', required: true,\n      placeholder: 'https://…', pattern: '^https?://' },\n    { key: 'method',  kind: 'select',  label: 'Method', default: 'GET',\n      options: [ { value: 'GET', label: 'GET' }, { value: 'POST', label: 'POST' } ] },\n    { key: 'body',    kind: 'textarea', label: 'Body', language: 'json' },\n    { key: 'apiKey',  kind: 'secret',  label: 'API key' },\n    { key: 'headers', kind: 'keyvalue', label: 'Extra headers' },\n    { key: 'tags',    kind: 'list',    label: 'Tags', maxItems: 10 },\n    { key: 'retries', kind: 'number',  label: 'Retries', min: 0, max: 5, integer: true },\n    { key: 'verbose', kind: 'boolean', label: 'Verbose logging', default: false },\n  ]\n}" },
            { kind: 'table', head: ['Kind', 'Value type', 'Notes'], rows: [
              ['`string`', 'string', 'Optional `pattern` regex, `placeholder`, `default`'],
              ['`textarea`', 'string', '`language: "text" | "json"` enables editor niceties'],
              ['`number`', 'number', '`min` / `max` / `integer`'],
              ['`boolean`', 'boolean', 'Rendered as a toggle'],
              ['`select`', 'string', 'Dropdown of `options`'],
              ['`list`', 'string[]', 'Growable rows, optional `maxItems`'],
              ['`secret`', 'string', 'Masked input; **encrypted at rest** in credential configs'],
              ['`keyvalue`', 'Record<string,string>', 'A string→string grid (headers, metadata…)'],
            ] },
            { kind: 'h2', text: 'Variable substitution' },
            { kind: 'p', text: 'By default, `{{variable}}` templates in field values are substituted **before** your code sees them. Disable per field with `substituteVariables: false` when braces are literal (e.g. a payload in another template language).' },
            { kind: 'callout', tone: 'note', text: 'Forms are capped at 40 fields, and every `key` must be unique and match `[a-zA-Z][a-zA-Z0-9_]*`. Values arrive in your executor already validated against the schema.' },
          ],
        },
      ],
    },
    {
      title: 'Extension Points',
      pages: [
        {
          slug: 'workflow-nodes',
          title: 'Workflow Nodes',
          description: 'Custom steps: executors, branching, prompts, and produced variables.',
          blocks: [
            { kind: 'p', text: 'A node contribution declares the canvas-facing surface (label, icon, category, config form); a `NodeExecutor` implements the behavior.' },
            { kind: 'h2', text: 'The executor contract' },
            { kind: 'code', lang: 'ts', title: 'NodeExecutor', code: "interface NodeExecuteInput {\n  config: Record<string, unknown>;   // validated against your configSchema\n  runtime: Record<string, string>;   // read-only snapshot of run variables\n  signal: AbortSignal;               // honour cancellation!\n}\n\ninterface NodeExecuteResult {\n  message?: string;                    // shown in the run panel\n  variables?: Record<string, string>;  // merged into the run's runtime\n  branch?: string;                     // branching nodes: which edge to take\n}" },
            { kind: 'h2', text: 'Branching nodes' },
            { kind: 'p', text: 'Declare `branching: true` and return a `branch` handle; the canvas renders labelled output edges and the runtime routes along the returned one. The `approval-dialog-node` example routes `approved` / `rejected` from a dialog outcome.' },
            { kind: 'h2', text: 'Prompting the user' },
            { kind: 'p', text: 'Declare an `input` block and the host shows a **native prompt before your executor runs** — the same modal the built-in user-input node uses. Collected values are merged into the runtime and visible to your executor. Field kinds: `string`, `secret`, `number`, `boolean`, `select`, `keyvalue`; `filledAtRuntime: true` turns select/keyvalue presets into growable run-time editors.' },
            { kind: 'code', lang: 'json', title: 'manifest — node with prompt', code: '{\n  "kind": "confirm-deploy",\n  "label": "Confirm deployment",\n  "branching": true,\n  "configSchema": { "fields": [] },\n  "input": {\n    "message": "Deploy {{service}} to production?",\n    "fields": [\n      { "variable": "approver", "kind": "string", "label": "Your name", "required": true },\n      { "variable": "strategy", "kind": "select", "label": "Strategy",\n        "options": ["rolling", "blue-green", "canary"], "default": "rolling" }\n    ]\n  }\n}' },
            { kind: 'h2', text: 'Declaring produced variables' },
            { kind: 'p', text: 'So later steps get `{{…}}` autocomplete *without running your plugin*, declare what you write: `producesVariables: [{ source: "config", key: "variable" }]` (the name is whatever the user typed into config field `variable`) or `{ source: "literal", name: "response_time" }` (a fixed name). Prompted `input` fields are counted automatically.' },
            { kind: 'callout', tone: 'warning', text: 'Runtime variables are **strings**. Serialize structured data as JSON and document the shape; number/boolean prompt fields submit their string form.' },
          ],
        },
        {
          slug: 'request-types',
          title: 'Request Types',
          description: 'New protocols with their own payload editor, badge, and response rendering.',
          blocks: [
            { kind: 'p', text: 'A request-type contribution puts a whole new protocol into the collection tree. You declare a `payloadSchema` (drives the editor), a `summary` (how it renders in lists), and implement a `RequestTypeProvider`.' },
            { kind: 'code', lang: 'json', title: 'manifest — request type', code: '{\n  "type": "nats",\n  "label": "NATS Publish",\n  "icon": "send",\n  "payloadSchema": {\n    "fields": [\n      { "key": "server",  "kind": "string", "label": "Server URL", "required": true },\n      { "key": "subject", "kind": "string", "label": "Subject",    "required": true },\n      { "key": "payload", "kind": "textarea", "label": "Message", "language": "json" }\n    ]\n  },\n  "summary": { "badge": "NATS", "targetKey": "subject" }\n}' },
            { kind: 'p', text: '`summary.badge` (≤10 chars) shows where HTTP shows the method; `summary.targetKey` names the payload key rendered where HTTP shows the URL.' },
            { kind: 'h2', text: 'The provider contract' },
            { kind: 'code', lang: 'ts', title: 'RequestTypeProvider.execute', code: "async execute({ payload, artifacts, options, signal }) {\n  // payload: validated + variable-substituted form values\n  // artifacts: auth headers/query/cookies if the request has auth configured\n  const result = await publish(payload, { timeout: options.timeoutMs, signal });\n  return {\n    ok: true,\n    summary: { label: 'PUBLISHED', tone: 'success', code: 'OK' },\n    metadata: { subject: String(payload.subject) },\n    body: JSON.stringify(result, null, 2),\n    bodyKind: 'json',\n  };\n}" },
            { kind: 'h2', text: 'The ProtocolResult' },
            { kind: 'table', head: ['Field', 'Purpose'], rows: [
              ['`ok`', 'Overall success; drives the status chip tone with `summary`'],
              ['`summary`', '`{ label, tone, code? }` — the chip (\'200 OK\' equivalent); `code` is what status-based tests read'],
              ['`metadata`', 'Header-like map rendered as the response metadata table'],
              ['`body` / `bodyKind`', 'Text (or base64 for `binary`); kind selects the viewer'],
              ['`error`', 'Set when the request failed before producing a response'],
              ['`protocol`', 'Type-specific extras, passed through to scripts and extraction untouched'],
            ] },
            { kind: 'callout', tone: 'note', text: 'Apply `artifacts.headers` wherever your protocol has a header/metadata concept — that is the contract that makes [auth providers](/plugins/auth-providers) compose with custom protocols.' },
            { kind: 'p', text: 'For live bidirectional protocols, add `interactive: true` and implement `openConnection` — see [Interactive Sessions](/plugins/interactive-sessions).' },
          ],
        },
        {
          slug: 'interactive-sessions',
          title: 'Interactive Sessions',
          description: 'Live connections: openConnection, event frames, and lifecycle state.',
          blocks: [
            { kind: 'p', text: 'Declaring `interactive: true` on a request type gives it a **live session mode**: instead of one-shot `execute()`, the host calls your `openConnection()` and renders a session panel with an event log and (optionally) a send bar.' },
            { kind: 'code', lang: 'ts', title: 'openConnection', code: "openConnection({ payload, signal, emit, setState }) {\n  const socket = connect(String(payload.url));\n\n  socket.on('open', () => setState('open'));\n  socket.on('message', (data) => emit({ direction: 'received', data: String(data) }));\n  socket.on('error', (err) => setState('error', { error: String(err) }));\n  socket.on('close', (code) => setState('closed', { code }));\n  signal.addEventListener('abort', () => socket.close());\n\n  return {\n    send(data) {\n      socket.send(data);\n      emit({ direction: 'sent', data });\n    },\n    close() {\n      socket.close();\n    },\n  };\n}" },
            { kind: 'h2', text: 'The pieces' },
            { kind: 'table', head: ['API', 'Purpose'], rows: [
              ['`emit(event)`', 'Push a frame to the session log. `direction`: sent / received / info / error; `kind` tags frames (e.g. an SSE event name)'],
              ['`setState(state, info?)`', 'Report lifecycle: `open`, `closed`, or `error`. The latter two end the session'],
              ['returned `send?`', 'Present → the panel shows a send bar (bidirectional protocols)'],
              ['returned `close()`', 'Called when the user ends the session or the app shuts down'],
              ['`signal`', 'Aborts on cancel — always wire it to your transport'],
            ] },
            { kind: 'callout', tone: 'warning', text: 'Report `setState(\'closed\')` (or `\'error\'`) in **every** termination path. A session that never reports closure keeps the UI in a live state until the user force-closes it.' },
            { kind: 'p', text: 'The `interactive-echo` example is a complete, dependency-free reference implementation.' },
          ],
        },
        {
          slug: 'auth-providers',
          title: 'Auth Providers',
          description: 'Custom signing schemes with encrypted credential storage.',
          blocks: [
            { kind: 'p', text: 'An auth provider adds a scheme to the credential editor. Its `configSchema` drives the editor — **`secret` fields are encrypted at rest automatically** — and its `apply()` turns a config plus request context into signing artifacts.' },
            { kind: 'code', lang: 'ts', title: 'AuthProvider', code: "ctx.registerAuthProvider('hmac', {\n  async apply({ config, ctx: req }) {\n    const ts = Date.now().toString();\n    const signature = hmacSha256(\n      String(config.secret),\n      `${req.method ?? 'GET'}\\n${req.url}\\n${ts}`\n    );\n    return {\n      headers: { 'X-Timestamp': ts, 'X-Signature': signature },\n      query: {},\n      cookies: {},\n    };\n  },\n});" },
            { kind: 'h2', text: 'The AuthArtifacts contract' },
            { kind: 'p', text: '`apply()` returns three maps — `headers`, `query`, `cookies`. Return empty maps for concepts your scheme has none of. The executing request type merges them into the outgoing request; custom request types are required to apply `headers` wherever their protocol has a header/metadata concept, so your provider composes with plugins you have never heard of.' },
            { kind: 'h2', text: 'The ApplyContext' },
            { kind: 'p', text: 'You receive `{ method?, url, headers?, body? }` — enough for signature schemes that hash the request. Non-HTTP request types may omit `method` and `body`; handle their absence.' },
            { kind: 'callout', tone: 'tip', text: 'Config values arrive variable-substituted, so users can put `{{apiSecret}}` in a secret field and rotate it per workspace.' },
          ],
        },
        {
          slug: 'importers',
          title: 'Importers',
          description: 'Teach the import dialog new formats.',
          blocks: [
            { kind: 'p', text: 'An importer turns text (pasted, from a file, or fetched from a URL) into a collection. You declare `sourceTypes` and optional `fileExtensions`; the import dialog lists your format automatically.' },
            { kind: 'code', lang: 'ts', title: 'Importer', code: "ctx.registerImporter('csv', {\n  detect(content) {\n    // cheap sniff — must never throw\n    return content.split('\\n')[0]?.toLowerCase().includes('method,path');\n  },\n  async parse({ content, sourceName, signal }) {\n    const rows = parseCsv(content);\n    return {\n      title: sourceName ?? 'CSV import',\n      version: '1.0',\n      baseUrl: 'https://api.example.com',\n      operations: rows.map((r) => ({\n        method: r.method.toUpperCase(),\n        path: r.path,\n        url: `https://api.example.com${r.path}`,\n        name: r.name || `${r.method} ${r.path}`,\n        tag: r.folder || null,\n      })),\n    };\n  },\n});" },
            { kind: 'h2', text: 'How results become collections' },
            { kind: 'p', text: 'You return an `ImportedCollection` — title, version, baseUrl, and flat `operations`. **The host generates the collection**: one folder per distinct `tag` (null lands at the root), one request per operation, with the badge from `method`. You never touch the database.' },
            { kind: 'h2', text: 'detect() etiquette' },
            { kind: 'ul', items: [
              'Sniff cheaply — first line, magic prefix, a light regex. `detect` runs against every candidate import.',
              'Never throw; return `false` for anything unrecognized.',
              'Be conservative: a false `true` steals imports from other formats.',
            ] },
            { kind: 'callout', tone: 'note', text: '`fileExtensions` (lowercase, with the dot: `[".csv"]`) pre-filters the file picker; `sourceTypes: ["text", "url"]` controls which import tabs offer your format.' },
          ],
        },
      ],
    },
    {
      title: 'Runtime API',
      pages: [
        {
          slug: 'plugin-context',
          title: 'PluginContext API',
          description: 'Logging, storage, variables, network, and registration — the ctx object.',
          blocks: [
            { kind: 'p', text: '`activate(ctx)` receives the **PluginContext** — your entire API surface. Registration methods must be called during activation; service properties remain usable for the plugin\'s lifetime.' },
            { kind: 'h2', text: 'Always available' },
            { kind: 'table', head: ['Member', 'Signature', 'Notes'], rows: [
              ['`pluginId`', '`string`', 'Your manifest id'],
              ['`log`', '`info/warn/error(message, data?)`', 'Structured logs, visible in Plugin Manager → details'],
              ['`storage.get`', '`(key) => Promise<string \\| undefined>`', 'Per-plugin persistent KV store'],
              ['`storage.set`', '`(key, value) => Promise<void>`', 'Values are strings — JSON-encode objects'],
              ['`storage.delete`', '`(key) => Promise<void>`', ''],
            ] },
            { kind: 'h2', text: 'Capability-gated' },
            { kind: 'table', head: ['Member', 'Requires', 'Signature'], rows: [
              ['`variables.resolve`', '`variables:read`', '`(template) => Promise<string>` — substitutes `{{vars}}`'],
              ['`variables.set`', '`variables:write`', '`(scope: "workspace" \\| "global", key, value) => Promise<void>`'],
              ['`fetch`', '`network`', 'The standard `fetch` API for outbound HTTP'],
              ['`ui.showDialog`', '`ui:dialog`', 'See [Dialogs](/plugins/dialogs)'],
            ] },
            { kind: 'callout', tone: 'warning', text: 'Gated members are `undefined` when the capability was not granted — check before use and degrade gracefully.' },
            { kind: 'h2', text: 'Registration' },
            { kind: 'code', lang: 'ts', code: "ctx.registerNodeExecutor(kind, executor);     // NodeExecutor\nctx.registerRequestType(type, provider);      // RequestTypeProvider\nctx.registerAuthProvider(type, provider);     // AuthProvider\nctx.registerImporter(id, importer);           // Importer" },
            { kind: 'p', text: 'Keys are the **unqualified** contribution keys from your manifest; the host applies the `plugin:<id>/` namespace.' },
            { kind: 'h2', text: 'Storage patterns' },
            { kind: 'code', lang: 'ts', title: 'caching with storage', code: "async function cachedLookup(ctx: PluginContext, key: string) {\n  const hit = await ctx.storage.get(`cache:${key}`);\n  if (hit) return JSON.parse(hit);\n  const fresh = await expensiveLookup(key);\n  await ctx.storage.set(`cache:${key}`, JSON.stringify(fresh));\n  return fresh;\n}" },
          ],
        },
        {
          slug: 'dialogs',
          title: 'Dialogs',
          description: 'Host-rendered modal dialogs with declarative forms.',
          blocks: [
            { kind: 'p', text: 'With the `ui:dialog` capability, `ctx.ui.showDialog()` shows a modal **rendered entirely by the host** — always naming your plugin, so users know who is asking. Plugin code never draws anything (ADR-0010); the dialog is pure data.' },
            { kind: 'code', lang: 'ts', title: 'confirm + collect', code: "const outcome = await ctx.ui.showDialog({\n  title: 'Deploy service',\n  message: 'Choose the rollout strategy for {{service}}.',\n  form: {\n    fields: [\n      { key: 'strategy', kind: 'select', label: 'Strategy', default: 'rolling',\n        options: [\n          { value: 'rolling', label: 'Rolling' },\n          { value: 'canary', label: 'Canary' },\n        ] },\n      { key: 'confirm', kind: 'boolean', label: 'I understand this affects production' },\n    ],\n  },\n  okLabel: 'Deploy',\n});\n\nif (outcome.cancelled || outcome.values.confirm !== true) {\n  return { branch: 'rejected', message: 'Deployment not confirmed' };\n}\nreturn { branch: 'approved', variables: { strategy: String(outcome.values.strategy) } };" },
            { kind: 'h2', text: 'Behavior' },
            { kind: 'ul', items: [
              'Same [form language](/plugins/forms) as config schemas; submitted `values` are validated before you see them.',
              'No `form` → a plain confirm; `values` comes back empty.',
              'Limits: `title` ≤ 80 chars, `message` ≤ 1000 chars.',
              '**Headless runs resolve as cancelled** — a workflow triggered without a window must still terminate sensibly, so always handle `cancelled`.',
            ] },
            { kind: 'callout', tone: 'tip', text: 'For prompts that should happen on every run of a node, prefer the manifest\'s declarative `input` block — it needs no capability and shows up in the node\'s documentation automatically. Reach for `ui.showDialog` when the prompt is conditional.' },
          ],
        },
      ],
    },
    {
      title: 'Shipping',
      pages: [
        {
          slug: 'testing-and-debugging',
          title: 'Testing & Debugging',
          description: 'Unit-test executors, integration-test packages, and read host logs.',
          blocks: [
            { kind: 'h2', text: 'Unit testing' },
            { kind: 'p', text: 'Executors are plain objects — no host required. Inject a fake context and assert on results:' },
            { kind: 'code', lang: 'ts', title: 'uuid-node.test.ts (vitest)', code: "import { describe, expect, it } from 'vitest';\nimport plugin from '../src';\n\nfunction fakeContext() {\n  const executors = new Map();\n  return {\n    ctx: {\n      pluginId: 'test',\n      log: { info() {}, warn() {}, error() {} },\n      storage: new Map() as never,\n      registerNodeExecutor: (k: string, e: unknown) => executors.set(k, e),\n      registerRequestType() {}, registerAuthProvider() {}, registerImporter() {},\n    },\n    executors,\n  };\n}\n\ndescribe('uuid node', () => {\n  it('writes the configured variable', async () => {\n    const { ctx, executors } = fakeContext();\n    await plugin.activate(ctx as never);\n    const result = await executors.get('uuid').execute({\n      config: { variable: 'id' },\n      runtime: {},\n      signal: new AbortController().signal,\n    });\n    expect(result.variables?.id).toMatch(/^[0-9a-f-]{36}$/);\n  });\n});" },
            { kind: 'h2', text: 'Integration testing' },
            { kind: 'p', text: 'The app\'s own suite loads the bundled example plugins as fixtures. For your plugin, the highest-value integration check is simply: build, install into a dev copy of API Workbench, and exercise each contribution once.' },
            { kind: 'h2', text: 'Debugging' },
            { kind: 'ul', items: [
              '`ctx.log.*` output lands in **Plugin Manager → your plugin → details**, with data objects serialized.',
              'Run failures show your executor\'s thrown error message in the run log — throw `Error` instances with actionable messages.',
              'Activation failures list the mismatch (unregistered contribution, unmanifested registration, SDK range) in the same details view.',
              'In dev builds, the plugin host process can be inspected with standard Node tooling.',
            ] },
            { kind: 'callout', tone: 'tip', text: 'Honour `signal` in anything that waits. Cancellation bugs are the most common review feedback — and the easiest to test: abort and assert your promise rejects promptly.' },
          ],
        },
        {
          slug: 'packaging-and-publishing',
          title: 'Packaging & Publishing',
          description: 'Bundle layout, validation, and distributing your plugin.',
          blocks: [
            { kind: 'h2', text: 'Package layout' },
            { kind: 'code', lang: 'text', code: 'my-plugin/\n├─ manifest.json        # required, at the root\n├─ dist/\n│  └─ index.cjs         # the bundled CommonJS entry (manifest.main)\n├─ README.md            # recommended\n└─ LICENSE              # recommended' },
            { kind: 'ul', items: [
              '**One file of code.** Bundle all dependencies into the CJS entry (esbuild/rollup). The host loads exactly `manifest.main`; stray `node_modules` are dead weight.',
              'Keep packages lean — no build inputs, no tests, no source maps in the shipped artifact.',
              'Target the Node version of the host\'s Electron runtime; avoid native modules entirely (they cannot be rebuilt inside the host).',
            ] },
            { kind: 'h2', text: 'Validation before shipping' },
            { kind: 'p', text: 'Install your built package into API Workbench via **Plugin Manager → Install from file…**. The loader runs the same validation your users will hit: manifest schema, engine range, contribution key patterns, and activation symmetry. Fix everything it reports before publishing.' },
            { kind: 'h2', text: 'Distributing' },
            { kind: 'p', text: 'Today, distribution is a zip/folder users install from file — publish releases on your own GitHub repo. The manifest\'s `signature` field is reserved for the planned marketplace flow ([security & signing](/plugins/security-and-signing)); packages published now will remain installable.' },
            { kind: 'callout', tone: 'note', text: 'Name your repo `api-workbench-plugin-<name>` and tag it `api-workbench-plugin` so users can find it — the future marketplace will index that convention.' },
          ],
        },
        {
          slug: 'versioning-and-migration',
          title: 'Versioning & Migration',
          description: 'SDK compatibility, plugin semver discipline, and migrating stored state.',
          blocks: [
            { kind: 'h2', text: 'Two versions to manage' },
            { kind: 'table', head: ['Version', 'Where', 'Meaning'], rows: [
              ['Plugin version', '`manifest.version`', 'Your own semver — communicate changes to users'],
              ['SDK range', '`manifest.engines.sdk`', 'The host SDK versions you support, e.g. `^1.0.0`'],
            ] },
            { kind: 'p', text: 'The host refuses to activate a plugin whose SDK range it does not satisfy — a clear error instead of a runtime crash. The SDK itself follows semver: additions are minor, breaking contract changes are major.' },
            { kind: 'h2', text: 'Semver discipline for plugins' },
            { kind: 'ul', items: [
              '**Patch** — bug fixes, no config or behavior contract changes.',
              '**Minor** — new contributions, new *optional* config fields (with defaults).',
              '**Major** — removed/renamed contributions or config keys, changed variable output names, changed branch handles.',
            ] },
            { kind: 'p', text: 'Renaming a node `kind` or a `producesVariables` name is breaking even if the code is "the same" — existing workflows reference the old ids.' },
            { kind: 'h2', text: 'Migrating stored state' },
            { kind: 'p', text: 'Per-plugin storage persists across updates. Version your schema and migrate lazily:' },
            { kind: 'code', lang: 'ts', code: "const VERSION = '2';\n\nasync function ensureMigrated(ctx: PluginContext) {\n  const v = await ctx.storage.get('schema-version');\n  if (v === VERSION) return;\n  if (v === '1' || v === undefined) {\n    const old = await ctx.storage.get('cache');\n    if (old) await ctx.storage.set('cache', migrateV1(old));\n  }\n  await ctx.storage.set('schema-version', VERSION);\n}" },
            { kind: 'callout', tone: 'tip', text: 'Keep config forms backward compatible: add fields with `default`s rather than renaming keys, and old node configs keep validating.' },
          ],
        },
        {
          slug: 'security-and-signing',
          title: 'Security & Signing',
          description: 'The threat model, what the sandbox guarantees, and the signing roadmap.',
          blocks: [
            { kind: 'h2', text: 'What the sandbox guarantees' },
            { kind: 'ul', items: [
              'Plugin code executes in an **isolated utility process**: no Electron APIs, no renderer/DOM, no database handles, no main-process modules (lint-fenced and process-enforced).',
              'Every host call crosses a **Zod-validated RPC** — malformed messages are rejected on both sides.',
              'The **capability broker** checks grants per call, so revocation is immediate.',
              'Inputs to your code are schema-validated; outputs from your code are schema-validated before the host uses them.',
              'Secrets are substituted in the main process; plugins cannot read secret plaintext.',
            ] },
            { kind: 'h2', text: 'What it does not guarantee' },
            { kind: 'p', text: 'A plugin granted `network` can exfiltrate whatever *it* is given — config values, resolved variables, dialog answers. The grant screen is the user\'s informed-consent moment; as an author, request the minimum and document why each capability is needed.' },
            { kind: 'h2', text: 'Authoring guidelines' },
            { kind: 'ul', items: [
              'Never ask users to place secrets in non-`secret` fields.',
              'Do not proxy arbitrary URLs from config through `ctx.fetch` without saying so in your README.',
              'Pin and audit your bundled dependencies — they ship inside your artifact.',
              'Fail closed: absent capability → degraded feature, not a workaround.',
            ] },
            { kind: 'h2', text: 'Signing (roadmap)' },
            { kind: 'p', text: 'The manifest\'s `signature` field is **reserved for marketplace package signing** and ignored in v1. The planned flow: publishers sign the package hash, the host verifies at install, and tampered packages refuse to install. Unsigned side-loading will remain possible with an explicit warning — this is your machine.' },
            { kind: 'callout', tone: 'danger', title: 'For users', text: 'Treat plugins like any software you run: prefer source-available plugins, read the capability list, and be suspicious of capability requests that do not match the plugin\'s purpose.' },
          ],
        },
        {
          slug: 'best-practices',
          title: 'Best Practices',
          description: 'Patterns that make plugins fast, predictable, and pleasant to review.',
          blocks: [
            { kind: 'h2', text: 'Behavior' },
            { kind: 'ul', items: [
              '**Honour `AbortSignal` everywhere.** Wire it into fetches, timers, and connections; test cancellation.',
              '**Be deterministic.** Same config + runtime in, same result out. Isolate nondeterminism (time, randomness) and document it.',
              '**Return, don\'t log, your outcome.** `message` in a node result reads better in the run panel than three log lines.',
              '**Keep `detect()` and `activate()` fast.** Both sit on interactive paths; defer heavy work to first execution.',
            ] },
            { kind: 'h2', text: 'Configuration' },
            { kind: 'ul', items: [
              'Give every field a `label`, a `description`, and a sensible `default` — your config form *is* your UX.',
              'Use `select` over free-text when values are enumerable; use `pattern` to catch typos early.',
              'Declare `producesVariables` so downstream autocomplete works — it is the difference between a node that feels native and one that feels bolted on.',
            ] },
            { kind: 'h2', text: 'Robustness' },
            { kind: 'ul', items: [
              'Throw `Error`s with actionable messages; they surface verbatim in the run log.',
              'Treat `runtime` values as untrusted strings: parse defensively, and JSON-encode structured outputs.',
              'Handle headless dialogs (`cancelled: true`) and absent capabilities without crashing.',
            ] },
            { kind: 'h2', text: 'Package hygiene' },
            { kind: 'ul', items: [
              'One extension point per plugin unless they genuinely belong together.',
              'Ship a README with a capability rationale and a worked example.',
              'Keep the bundle dependency-light; every byte ships to every user.',
            ] },
          ],
        },
        {
          slug: 'troubleshooting',
          title: 'Troubleshooting',
          description: 'Common plugin failures and how to fix them.',
          blocks: [
            { kind: 'h2', text: 'Activation failed: contribution not registered' },
            { kind: 'p', text: 'Your manifest declares a contribution `activate()` never registered (or vice-versa). Registration must be **exactly symmetric** with the manifest. Check for typos between the manifest key and the string passed to `register…()` — remember keys are the *unqualified* form (`uuid`, not `plugin:…/uuid`).' },
            { kind: 'h2', text: 'Install rejected: manifest validation' },
            { kind: 'ul', items: [
              'Keys must match `[a-z][a-z0-9-]*` — no uppercase, no underscores.',
              '`engines.sdk` must be a valid semver range the host satisfies.',
              '`main` must point at a file that exists inside the package.',
              'Form schemas: unique field keys matching `[a-zA-Z][a-zA-Z0-9_]*`, ≤ 40 fields.',
            ] },
            { kind: 'h2', text: 'ctx.fetch / ctx.variables / ctx.ui is undefined' },
            { kind: 'p', text: 'The capability is not in your manifest, or the user declined it. Declare it in `capabilities` and handle absence gracefully either way — see [Capabilities & Permissions](/plugins/capabilities-and-permissions).' },
            { kind: 'h2', text: 'My node runs but later steps cannot see its variables' },
            { kind: 'p', text: 'Return them in `variables` on the execute result — writing to the `runtime` input object does nothing (it is a read-only snapshot). For autocomplete before any run, also declare `producesVariables` in the manifest.' },
            { kind: 'h2', text: 'Dialog resolves as cancelled instantly' },
            { kind: 'p', text: 'The run is headless (no window) — by design, dialogs cancel so automation terminates. Branch on `cancelled` and choose a safe default path.' },
            { kind: 'h2', text: 'Native module errors in the host' },
            { kind: 'p', text: 'Native Node addons are unsupported in plugin bundles. Replace with pure-JS/WASM alternatives.' },
            { kind: 'callout', tone: 'tip', text: 'Still stuck? Compare against the closest [example plugin](/examples) — the eight examples are integration-tested against every host release.' },
          ],
        },
        {
          slug: 'faq',
          title: 'Plugin FAQ',
          description: 'Quick answers for plugin authors.',
          blocks: [
            { kind: 'h2', text: 'Can plugins render custom UI?' },
            { kind: 'p', text: 'No — by design. Config forms, payload editors, prompts, and dialogs are all declared as data and rendered by the host (ADR-0010). This is what makes the capability model enforceable. If the [form language](/plugins/forms) is missing a field kind you need, open a feature request.' },
            { kind: 'h2', text: 'Can a plugin talk to another plugin?' },
            { kind: 'p', text: 'Not directly. Compose through workflows: one plugin\'s node writes runtime variables the next node reads.' },
            { kind: 'h2', text: 'Can I use TypeScript?' },
            { kind: 'p', text: 'Yes — the SDK is types-only and designed for it. Bundle to a single CJS file with esbuild.' },
            { kind: 'h2', text: 'Can my node keep state between steps?' },
            { kind: 'p', text: 'Within a run, pass state through runtime variables. Across runs, use `ctx.storage`. In-memory module state survives while the plugin stays enabled but is lost on restarts — never rely on it for correctness.' },
            { kind: 'h2', text: 'How do I read the response of a previous workflow step?' },
            { kind: 'p', text: 'You don\'t, directly — steps communicate via runtime variables. Have the user (or an Extract node) map the value you need into a variable and reference it in your config.' },
            { kind: 'h2', text: 'Is there a marketplace?' },
            { kind: 'p', text: 'Planned — the architecture is marketplace-ready (namespaced ids, reserved `signature`, capability grants). Until then, distribute via GitHub releases; see [Packaging & Publishing](/plugins/packaging-and-publishing).' },
            { kind: 'h2', text: 'What Node APIs are available?' },
            { kind: 'p', text: 'The host runs plugins in an Electron utility process: standard Node built-ins (`crypto`, `buffer`, `url`, timers…) work; native addons do not; and anything privileged (fs, net beyond `ctx.fetch`) should be considered off-limits and may be restricted further — design within the capability model.' },
          ],
        },
      ],
    },
  ],
};
